#!/usr/local/public/bin/Rscript --vanilla --slave --no-site-file
# mehalocoa.r version="20141117"
#created by Yann GUITTON ThalassOMICS core facility from Corsaire plateforme

#Redirect all stdout to the log file
log_file=file("cdf2rdata.log", open = "wt")
sink(log_file)
sink(log_file, type = "out")

library(MeHaloCoA)
library(batch) #necessary for parseCommandArgs function

source_local <- function(fname){
    argv <- commandArgs(trailingOnly = FALSE)
    base_dir <- dirname(substring(argv[grep("--file=", argv)], 8))
    source(paste(base_dir, fname, sep="/"))
}

#Import the different functions
# source_local("lib.r")
listArguments = parseCommandArgs(evaluate=FALSE) #interpretation of arguments given in command line as an R list of objects
print(listArguments)

#First check if the folder containing the chromatograms exists, if not exits with error
if (listArguments[["xfunction"]] == "CDF2RData") {
        library=listArguments[["library"]]
		dir(library)
		if(!file.exists(listArguments[["library"]])){
			error_message=paste("Cannot access the directory :",listArguments[["library"]],".Please verify if the directory exists or not.")
			print (error_message)
			stop(error_message)
		}
}
#image is an .RData file necessary to use the xsAnnotate object generated by CDF2RData or by CAMERA variable given by previous tools
if (!is.null(listArguments[["image"]])){
    load(listArguments[["image"]])
    listArguments[["image"]]=NULL
}


#saving the name of the function in a variable thefunction
thefunction = listArguments[["xfunction"]]
listArguments[["xfunction"]]=NULL #delete from the list of arguments

#Verification of xsAnnotate class before doing the cldetect job.

# if (thefunction == "cldetect") {
	# res=try(class(an[[1]]=="xsAnnotate"))
	# if (res != TRUE){
        	# error<-geterrmessage()
                # print (error)
                # print ("You must always use object from CDF2RData or groupFWHM. Otherwise it won't work for the cldetect step")
	# }

# }


if (thefunction == "CDF2RData") { #only CDF2RData use library
	library=listArguments[["library"]]
	listArguments[["library"]]=NULL #delete from the list of arguments
	an<-CDF2RData(indir=library,settingslist=listArguments)
	an
	#zip files of all CDF2RData outputs
	now<-format(Sys.time(), "Results_%Y_%B_%d_")
	system(paste('ls . | grep -e now | zip -r -@ "cdf2rdata.zip"'))
}


if (thefunction == "cldetect") { #only CDF2RData use library
	
	#read an from image and test it!
	if((class(an)=="xsAnnotate")==FALSE){
		xsAnnotate<-an[as.vector(which(lapply(an,function(x)class(x))=="xsAnnotate"))]
	}else
	{
		xsAnnotate<-an
	}
	print(xsAnnotate)

	if (length(xsAnnotate)>1){  
		print("several files")
		assign("matcl",vector(mode="list", length=length(xsAnnotate)), envir=as.environment(MeHaloCoAenv))
	   
	   #projectpdf is a function that avoid overwriting IFC.pdf
		MeHaloCoA:::projectpdf(dir=getwd(),projectName="IFC", ext="pdf")
		  mat<-list()
		  for (i in 1:length(xsAnnotate)){
			MeHaloCoAenv$matcl[[i]]<-do.call(cldetect,c(outdir=getwd(),xsAnnotate=xsAnnotate[[i]],listArguments))
		  }
		dev.off()
		
		for (i in 1:length(MeHaloCoAenv$matcl)){
			MeHaloCoAenv$matcl[[i]]<-cbind(basename(xsAnnotate[[i]]@xcmsSet@filepaths),MeHaloCoAenv$matcl[[i]])
			MeHaloCoAenv$matcl[[i]] <- data.frame(lapply(MeHaloCoAenv$matcl[[i]], as.character), stringsAsFactors=FALSE)
			colnames(MeHaloCoAenv$matcl[[i]])[1]<-"File"
		}
		mat<-do.call("rbind",MeHaloCoAenv$matcl)
		
		write.table(mat, file=file.path(getwd(), "halo_list_short.csv"), row.names=FALSE, sep="\t")
	}
	else{
	  MeHaloCoA:::projectpdf(dir=getwd(),projectName="IFC", ext="pdf")
		assign("matcl", do.call(cldetect,c(outdir=getwd(),xsAnnotate=xsAnnotate,listArguments)), envir=as.environment(MeHaloCoAenv))
	  dev.off()
	}

	
	#just to have a readable tsv for output in Galaxy web site
	if (file.exists("halo_list.csv")){
		data<-read.table("halo_list.csv", h=T, sep=",")
		write.table(data, file="halo_list.tsv", sep="\t", row.names=F)
	}
	
	if (file.exists("halo_list_short.csv")){
		data<-read.table("halo_list_short.csv", h=T, sep=",")
		write.table(data, file="halo_list_short.tsv", sep="\t", row.names=F)
	}
	#zip files of all cldetect outputs
	system(paste('ls . | grep -e "EICs_" -e "pdf$" -e "tsv$"  | zip -r -@ "cldetect.zip"'))
}


#delete the parameters to avoid the passage to the next tool in .RData image
rm(listArguments)

#saving R data in .Rdata file to save the variables used in the present tool
save.image(paste(thefunction,"RData",sep="."))

